baseURL = "https://danielmangum.com/goji/"
languageCode = "en-us"
title = "Goji"
theme = "project"
publishDir = "../docs"


[params]
    description = "Create, generate, and share any code with anyone."
    author_url = "http://danielmangum.com"
    project_url = "https://github.com/HashedDan/goji"
    project_documentation = "https://github.com/HashedDan/goji/wiki"
    github_project_name = "goji"
    github_user_name = "HashedDan"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
